name: Scraper
on:
  schedule:
    # https://www.mnb.hu/en/statistics/statistical-data-and-information/statistical-time-series/exchange-rates/fixing-and-publication-of-the-official-exchange-rates
    - cron: "25/5 9,10 * * 1-5"
    - cron: "55 16 * * 1-5"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/bootstrap
      - run: pnpm run fetch:mnb ${${{ github.event.schedule == '55 16 * * 1-5' }}:+--full}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update"
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
